/*
Trabajo Práctico Nº 4
DESARROLLO DE APLIC. CON BASES DE DATOS
2022
Alumno: ARIEL MIELE
Legajo: VINF011482
DNI: 34.434.704
*/

/*
OBJETIVO: Aplicar los conceptos teóricos y prácticos relevantes en la conformación de un almacén de datos.
Objetivos específicos para esta actividad:
- Reconocer componentes y características de un almacén de datos. 
- Aplicar los conceptos de un proceso ETL. 
- Implementar un proceso ETL mediante el lenguaje SQL.
*/

/* CONSIGNA:
El objetivo de este trabajo individual consiste en desarrollar un proceso ETL (Extracción, transformación y carga) utilizando lenguaje SQL, 
para completar la base de datos del Datawarehouse de la organización. 

Para ello se deben realizar las siguientes actividades:
1. Crear una base de datos denominada DWPedidos.
2. Crear las siguientes tablas en la base de datos DWPedidos (imágenes en el TP).
3. Cargar las tablas de la base de datos DWPedidos con los datos de la base de datos de PEDIDOS, mediante procedimientos almacenados desarrollados en SQL.
*/

-- Instrucciones para realizar el DROP de las tablas de la base de datos para comenzar desde 0 la ejecución

DROP TABLE DIMFECHAS CASCADE CONSTRAINTS;

DROP TABLE DIMPRODUCTOS CASCADE CONSTRAINTS;

-- Inicio de la creación de tablas en el Data Warehouse

-- Creación de la tabla DIMFECHAS
CREATE TABLE DIMFECHAS (
    ID_FEC INT GENERATED BY DEFAULT AS IDENTITY,
    FECHA DATE,
    DIA INT,
    MES INT,
    ANIO INT,
    PRIMARY KEY (ID_FEC)
);

-- Creación de la tabla DIMPRODUCTOS
CREATE TABLE DIMPRODUCTOS (
    ID_PRO INT GENERATED BY DEFAULT AS IDENTITY,
    IDPRODUCTO INT,
    DESCRIPCION VARCHAR (50),
    NOMBREPROVEEDOR VARCHAR (50),
    PRIMARY KEY (ID_PRO)
);

-- Creación de la tabla FACTPEDIDOS
CREATE TABLE FACTPEDIDOS (
    ID_CLI INT,
    ID_PRO INT,
    ID_FEC INT,
    CANTIDAD INT,
    TOTAL INT
);

-- Creación de la tabla DIMCLIENTES
CREATE TABLE DIMCLIENTES (
    ID_CLI INT GENERATED BY DEFAULT AS IDENTITY,
    IDCLIENTE INT,
    NOMBRE VARCHAR (50)
);

-- Fin de la creación de tablas para el Data Warehouse

-- Inicio de la creación de los procedimientos almacenados para la carga de datos

-- Procedimiento almacenado que permite cargar fechas
CREATE OR REPLACE PROCEDURE CARGAR_FECHAS ()
IS
-- Declaración de variables
BEGIN
-- Comienzo de la ejecución del procedimiento almacenado
INSERT INTO DIMFECHAS (
    
)
END;

-- Procedimiento almacenado que permite cargar productos
CREATE OR REPLACE PROCEDURE CARGAR_PRODUCTOS()
IS
END;

-- Procedimiento almacenado que permite cargar pedidos
CREATE OR REPLACE PROCEDURE CARGAR_PEDIDOS()
IS
END;

-- Procedimiento almacenado que permite cargar clientes
CREATE OR REPLACE PROCEDURE CARGAR_CLIENTES()
IS
END;

-- Fin de la creación de los procedimientos almacenados para la carga de datos