/*
Trabajo Práctico Nº 4
DESARROLLO DE APLIC. CON BASES DE DATOS
2022
Alumno: ARIEL MIELE
Legajo: VINF011482
DNI: 34.434.704
*/

/*
OBJETIVO: Aplicar los conceptos teóricos y prácticos relevantes en la conformación de un almacén de datos.
Objetivos específicos para esta actividad:
- Reconocer componentes y características de un almacén de datos. 
- Aplicar los conceptos de un proceso ETL. 
- Implementar un proceso ETL mediante el lenguaje SQL.
*/

/* CONSIGNA:
El objetivo de este trabajo individual consiste en desarrollar un proceso ETL (Extracción, transformación y carga) utilizando lenguaje SQL, 
para completar la base de datos del Datawarehouse de la organización. 

Para ello se deben realizar las siguientes actividades:
1. Crear una base de datos denominada DWPedidos.
2. Crear las siguientes tablas en la base de datos DWPedidos (imágenes en el TP).
3. Cargar las tablas de la base de datos DWPedidos con los datos de la base de datos de PEDIDOS, mediante procedimientos almacenados desarrollados en SQL.
*/

/*
Como estamos usando Oracle SQL y un esquema de Autonomouse Databases Online, 
vamos a trabajar dentro de la misma base de datos anterior (según lo indicado por el profesor en el video explicativo sobre el TP4).
Se mantienen los ejercicios generados durante los Trabajos Prácticos anteriores. Se indica con comentarios el inicio de la resolución del TP4.
*/

-- INICIO Resolución TP4

-- Instrucciones para realizar el DROP de las tablas de la base de datos para comenzar desde 0 la ejecución

DROP TABLE DIMFECHAS CASCADE CONSTRAINTS;

DROP TABLE DIMPRODUCTOS CASCADE CONSTRAINTS;

DROP TABLE DIMCLIENTES CASCADE CONSTRAINTS;

DROP TABLE FACTPEDIDOS CASCADE CONSTRAINTS;

-- Inicio de la creación de tablas en el Data Warehouse

-- Creación de la tabla DIMFECHAS
CREATE TABLE DIMFECHAS (
    ID_FEC INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    FECHA DATE,
    DIA INT,
    MES INT,
    ANIO INT,
    PRIMARY KEY (ID_FEC)
);

-- Creación de la tabla DIMPRODUCTOS
CREATE TABLE DIMPRODUCTOS (
    ID_PRO INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    IDPRODUCTO INT,
    DESCRIPCION VARCHAR (50),
    NOMBREPROVEEDOR VARCHAR (50),
    PRIMARY KEY (ID_PRO)
);

-- Creación de la tabla DIMCLIENTES
CREATE TABLE DIMCLIENTES (
    ID_CLI INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    IDCLIENTE INT,
    NOMBRE VARCHAR (50),
    PRIMARY KEY (ID_CLI)
);

-- Creación de la tabla FACTPEDIDOS
CREATE TABLE FACTPEDIDOS (
    ID_CLI INT NOT NULL,
    ID_PRO INT NOT NULL,
    ID_FEC INT NOT NULL,
    CANTIDAD INT NOT NULL,
    TOTAL INT NOT NULL,
    CONSTRAINT FK_FACTCLIENTES FOREIGN KEY (ID_CLI) REFERENCES DIMCLIENTES (ID_CLI),
    CONSTRAINT FK_FACTPRODUCTOS FOREIGN KEY (ID_PRO) REFERENCES DIMPRODUCTOS (ID_PRO),
    CONSTRAINT FK_FACTFECHAS FOREIGN KEY (ID_FEC) REFERENCES DIMFECHAS (ID_FEC)
);

-- Fin de la creación de tablas para el Data Warehouse

-- Comienzo de los DROP para los Procedimientos almacenados

DROP PROCEDURE CARGAR_FECHAS;

DROP PROCEDURE CARGAR_PRODUCTOS;

DROP PROCEDURE CARGAR_CLIENTES;

DROP PROCEDURE FACTURAR_PEDIDOS;

-- Fin de los DROP para los Procedimientos Almacenados

-- Inicio de la creación de los procedimientos almacenados para la carga de datos

-- Procedimiento almacenado que permite cargar fechas
CREATE OR REPLACE PROCEDURE CARGAR_FECHAS
IS
BEGIN
    INSERT INTO DIMFECHAS 
        (FECHA, DIA, MES, ANIO)
    SELECT DISTINCT
        FECHA, 
        EXTRACT (DAY FROM FECHA) AS DIA, 
        EXTRACT (MONTH FROM FECHA) AS MES, 
        EXTRACT (YEAR FROM FECHA) AS ANIO
    FROM PEDIDOS
    EXCEPTION;
END;

-- Ejecuta el procedimiento almacenado
EXECUTE CARGAR_FECHAS; 

-- Lee el contenido de la tabla DIMFECHAS
SELECT * FROM DIMFECHAS; 

-- Procedimiento almacenado que permite cargar productos
CREATE OR REPLACE PROCEDURE CARGAR_PRODUCTOS
IS
BEGIN
    INSERT INTO DIMPRODUCTOS 
        (IDPRODUCTO, DESCRIPCION, NOMBREPROVEEDOR)
    SELECT 
        IDPRODUCTO, 
        DESCRIPCION,
        NOMBREPROVEEDOR
    FROM PRODUCTOS 
    INNER JOIN PROVEEDORES
    ON PRODUCTOS.IDPROVEEDOR = PROVEEDORES.IDPROVEEDOR;
END;

-- Ejecuta el procedimiento almacenado
EXECUTE CARGAR_PRODUCTOS; 

-- Lee el contenido de la tabla DIMPRODUCTOS
SELECT * FROM DIMPRODUCTOS;

-- Procedimiento almacenado que permite cargar clientes
CREATE OR REPLACE PROCEDURE CARGAR_CLIENTES
IS
BEGIN
    INSERT INTO DIMCLIENTES 
        (IDCLIENTE, NOMBRE)
    SELECT 
        IDCLIENTE, 
        CONCAT(CONCAT(APELLIDO, ', '), NOMBRE) AS NOMBRE
    FROM CLIENTES
    EXCEPTION;
END;

-- Ejecuta el procedimiento almacenado
EXECUTE CARGAR_CLIENTES;

SELECT * FROM DIMCLIENTES;

-- Procedimiento almacenado que permite cargar pedidos
CREATE OR REPLACE PROCEDURE FACTURAR_PEDIDOS
IS
BEGIN
    INSERT INTO FACTPEDIDOS 
        (ID_CLI, ID_PRO, ID_FEC, CANTIDAD, TOTAL)
    SELECT 
    (SELECT ID_CLI FROM DIMCLIENTES WHERE IDCLIENTE = PEDIDOS.IDCLIENTE) AS ID_CLI,
    (SELECT ID_PRO FROM DIMPRODUCTOS WHERE IDPRODUCTO = DETALLEPEDIDOS.IDPRODUCTO) AS ID_PRO,
    (SELECT ID_FEC FROM DIMFECHAS WHERE FECHA = PEDIDOS.FECHA) AS ID_FEC,
    DETALLEPEDIDOS.CANTIDAD,
    DETALLEPEDIDOS.TOTAL
    FROM DETALLEPEDIDOS INNER JOIN PEDIDOS ON DETALLEPEDIDOS.NUMEROPEDIDO = PEDIDOS.NUMEROPEDIDO;
END;

-- Ejecuta el procedimiento almacenado
EXECUTE FACTURAR_PEDIDOS;

-- Muestra la tabla FACTPEDIDOS
SELECT * FROM FACTPEDIDOS;

-- Fin de la creación de los procedimientos almacenados para la carga de datos

-- FIN de la resolución del TP4